[package]
name = "rustyservice"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }
serde = { version = "1.0", features = ["derive"] }